/**
 * Created by spring4 on 20-11-2019.
 */

public with sharing class FederatedViewController {
   /* private final Open_Search__x opnSearch;

    public FederatedViewController(ApexPages.StandardController stdController) {
        this.opnSearch = (Open_Search__x)stdController.getRecord();
        System.debug(' FederatedViewController.FederatedViewController opnSearch.Title__c: ' + opnSearch.Title__c);
    }*/
}